# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 11:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('push_notifications', '0002_auto_20160106_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('active', models.BooleanField(default=True, help_text='Inactive devices will not be sent notifications', verbose_name='Is active')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('device_id', models.CharField(max_length=255, null=True, unique=True, verbose_name='Device ID')),
                ('registration_id', models.TextField(verbose_name='Registration ID')),
                ('device_type', models.IntegerField(choices=[(0, 'APNS'), (1, 'GCM')])),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='apnsdevice',
            name='user',
        ),
        migrations.RemoveField(
            model_name='gcmdevice',
            name='user',
        ),
        migrations.DeleteModel(
            name='APNSDevice',
        ),
        migrations.DeleteModel(
            name='GCMDevice',
        ),
        migrations.CreateModel(
            name='APNSDevice',
            fields=[
            ],
            options={
                'verbose_name': 'APNS device',
                'proxy': True,
            },
            bases=('push_notifications.device',),
        ),
        migrations.CreateModel(
            name='GCMDevice',
            fields=[
            ],
            options={
                'verbose_name': 'GCM device',
                'proxy': True,
            },
            bases=('push_notifications.device',),
        ),
    ]
