# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0003_auto_20160728_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('kwargs', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.IntegerField(choices=[(0, 'APNS'), (1, 'GCM')], editable=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='devices',
            field=models.ManyToManyField(related_name='sent_notifications', to='push_notifications.Device'),
        ),
    ]
